---

- hosts: all
  become: true
  tasks:

  - name: install apache and libapache2-mod-php packages
    package:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
      update_cache: yes
