---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: jenkins_master
  become: true
  roles:
    - jenkins_master
