---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and libapache2-mod-php packages
    package:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
      update_cache: yes

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    apt:
      name: mariadb-server
      state: latest

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
