---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and libapache2-mod-php packages
    tags: apache,ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
      update_cache: yes

  - name: copy defaul html file
    tags: apache
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba 
    package:
      name: samba
