- name: install apache and libapache2-mod-php packages
  tags: apache,ubuntu
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"  
    state: latest
    update_cache: yes 

- name: copy defaul html file
  tags: apache
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
